### ISSUE TITLE
util.py change to test certain U.3 drive

### ISSUE THREAD

**Issue by fftelles** [IBM/nvme-disk-qualifier#6]
Hi Drew,

I had brought up the modification below that enabled us to successfully test a Micron 7450 U.3 drive. Anthony Cozzolino and Michael Light had done the investigation to determine this:

util.py, line 38 

change from:

    process = subprocess.Popen(command, stdout=subprocess.PIPE,
                               stderr=subprocess.PIPE, shell=shell,
                               universal_newlines=True)

change to:

    process = subprocess.Popen(command, stdout=subprocess.PIPE,
                               stderr=subprocess.PIPE, shell=shell,
                               universal_newlines=True, errors="replace")

Thanks,
Felipe

**Comment by atthorst** [comment]
Fixed here: https://github.com/IBM/nvme-disk-qualifier/pull/7
